//
//  RepositoriesModels.swift
//  Github
//
//  Created by Rafael Almeida on 28/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Repositories
{
    enum Initial {
        struct Request {
            
        }
        
        struct Response {
            let repositories: Repository
        }
        
        struct ViewModel {
            let repositories: [RepositoryViewModel]
        }
    }
    
    enum Error {
        struct Response {
            let error: String
        }
        
        struct ViewModel {
            let error: String
        }
    }
}

struct RepositoryViewModel {
    var repositoryName: String
    var reposidotyDescription: String
    var ownerName: String
    var avatarUrl: String
    var stars: Int
    var forks: Int
}
